### ISSUE TITLE
isolate openblas/GPU things if only doing CPU scoring.

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#390]
```
We are evaluating DAI and I am having issues getting the scoring pipeline to run on a machine.

Using the instructions at http://docs.h2o.ai/driverless-ai/latest-stable/docs/userguide/scoring-package.html I spun up a AWS ec2 server with Ubuntu 16.04 x64 I attempted to follow the instructions to get the HTTP scoring service up and going but am having an issue, below is the stack trace on the error.


Traceback (most recent call last):
 File "http_server.py", line 12, in <module>
   from scoring_h2oai_experiment_ac97cf import Scorer
 File "/home/ubuntu/emm-pipe/http_server_env/lib/python3.6/site-packages/scoring_h2oai_experiment_ac97cf/__init__.py", line 1, in <module>
   from .scorer import Scorer
 File "/home/ubuntu/emm-pipe/http_server_env/lib/python3.6/site-packages/scoring_h2oai_experiment_ac97cf/scorer.py", line 6, in <module>
   from h2oaicore.transformer_utils import fit_transform_batch
 File "h2oaicore/__init__.py", line 5, in init h2oaicore.__init__
 File "h2oaicore/ga_misc.py", line 38, in init h2oaicore.ga_misc
 File "/home/ubuntu/emm-pipe/http_server_env/lib/python3.6/site-packages/h2o4gpu/__init__.py", line 11, in <module>
   from .solvers.pogs import Pogs
 File "/home/ubuntu/emm-pipe/http_server_env/lib/python3.6/site-packages/h2o4gpu/solvers/__init__.py", line 8, in <module>
   from ..solvers.elastic_net import ElasticNetH2O
 File "/home/ubuntu/emm-pipe/http_server_env/lib/python3.6/site-packages/h2o4gpu/solvers/elastic_net.py", line 15, in <module>
   from h2o4gpu.linear_model import coordinate_descent as sk
 File "/home/ubuntu/emm-pipe/http_server_env/lib/python3.6/site-packages/h2o4gpu/linear_model/__init__.py", line 15, in <module>
   from .least_angle import (Lars, LassoSklearnLars, lars_path, LarsCV, LassoSklearnLarsCV,
 File "/home/ubuntu/emm-pipe/http_server_env/lib/python3.6/site-packages/h2o4gpu/linear_model/least_angle.py", line 23, in <module>
   from ..utils import arrayfuncs, as_float_array, check_X_y, deprecated
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

I have attached to this email the entire console session when following the instructions from the documentation. If it is helpful I can also get a s3 link for the scoring pipeline package (~2GB) and the logs from the DAI run that built the scoring pipeline package (~803MB).

￼￼￼￼
[1:50] ￼
Any idea why this is happening with the scoring package ?
```

**Comment by Kzernobog** [comment]
Any luck on this??? I'm having the same problem when trying to run ```import h2o4gpu``` in a python shell on a remote server. The server has user instances for GPU. You can load the CUDA and CUDNN of your choice on your bash instance before running it.

I'm getting the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aditya/numerai/h20_env3/lib/python3.6/site-packages/h2o4gpu/__init__.py", line 113, in <module>
    from .solvers.truncated_svd import TruncatedSVDH2O
  File "/home/aditya/numerai/h20_env3/lib/python3.6/site-packages/h2o4gpu/solvers/__init__.py", line 8, in <module>
    from ..solvers.elastic_net import ElasticNetH2O
  File "/home/aditya/numerai/h20_env3/lib/python3.6/site-packages/h2o4gpu/solvers/elastic_net.py", line 15, in <module>
    from h2o4gpu.linear_model import coordinate_descent as sk
  File "/home/aditya/numerai/h20_env3/lib/python3.6/site-packages/h2o4gpu/linear_model/__init__.py", line 15, in <module>
    from .least_angle import (Lars, LassoSklearnLars, lars_path, LarsCV, LassoSklearnLarsCV,
  File "/home/aditya/numerai/h20_env3/lib/python3.6/site-packages/h2o4gpu/linear_model/least_angle.py", line 23, in <module>
    from ..utils import arrayfuncs, as_float_array, check_X_y, deprecated
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
```

**Comment by TraderJair** [comment]
I have the same problem here, any solutions, 7 months later, no one solve it?
