### ISSUE TITLE
ppc not building anymore

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#646]
http://mr-0xc1:8080/job/h2o4gpu-ppc64le-cuda9/job/master/24/consoleFull
http://mr-0xc1:8080/job/h2o4gpu-ppc64le-cuda9/job/master/25/consoleFull

The two logs: 
[consoles.zip](https://github.com/h2oai/h2o4gpu/files/2199477/consoles.zip)

For ppc h2o4gpu was fine on build 24 but not 25, but only diff was things that explicitly aren't run for ppc:

```
git diff fd44ea30f9ec32da462d031092c16173a159030c ad2d4a92ec282ef29bc3924cddb179ca38fa0ece
```

```
diff --git a/Dockerfile-build b/Dockerfile-build
index 9e688ea..b3988f8 100644
--- a/Dockerfile-build
+++ b/Dockerfile-build
@@ -181,9 +181,9 @@ RUN \
     cd boost_1_58_0 && \
     export PYTHONPATH=/opt/h2oai/h2o4gpu/python/ && \
     ./bootstrap.sh --prefix=/opt/boost/ --with-python=python3 && \
-    export CPPFLAGS="-I/opt/h2oai/h2o4gpu/python/include/python3.6m/" && \
+    export CPPFLAGS="-I/opt/h2oai/h2o4gpu/python/include/python3.6m/ -fPIC" && \
     export C_INCLUDE_PATH="/opt/h2oai/h2o4gpu/python/include/python3.6m/" ; export CPLUS_INCLUDE_PATH="/opt/h2oai/h2o4gpu/python/include/python3.6m/" && \
-    ./b2 -a -d0 install --prefix=/opt/boost/ --with=all -j 20 && \
+    ./b2 link=static -a -d0 install --prefix=/opt/boost/ --with=all -j 20 cxxflags="-fPIC -I /opt/h2oai/h2o4gpu/python/include/python3.6m/" && \
     cd /usr/include ; rm -rf boost ; ln -s /opt/boost/include/boost . && \
     cd /usr/lib64/ ; rm -rf libboost* ; cp -a /opt/boost/lib/* . && \
     cd / ; \
diff --git a/Makefile b/Makefile
index 9208dff..ca7161a 100644
--- a/Makefile
+++ b/Makefile
@@ -103,7 +103,7 @@ lightgbm:
        @echo "sudo apt-get install libboost-dev libboost-system-dev libboost-filesystem-dev cmake"
        if [ `arch` != "ppc64le" ]; then \
        rm -rf LightGBM ; result=`git clone --recursive https://github.com/Microsoft/LightGBM` && \
-       cd LightGBM && (rm -rf build || true) && mkdir -p build ; cd build && cmake .. -DUSE_GPU=1 -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DOpenCL_LIBRARY=$(CUDA_HOME)/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIR=$(CUDA_HOME)/include/ && \
+       cd LightGBM && (rm -rf build || true) && mkdir -p build ; cd build && cmake .. -DUSE_GPU=1 -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DOpenCL_LIBRARY=$(CUDA_HOME)/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIR=$(CUDA_HOME)/include/ -DBOOST_ROOT=/opt/boost -DBoost_USE_STATIC_LIBS=1 && \
        make OPENCL_HEADERS=$(CUDA_HOME)/targets/x86_64-linux/include LIBOPENCL=$(CUDA_HOME)/targets/x86_64-linux/lib -j && cd .. && \
        cd python-package &&  sed -i 's/self\.gpu \= 0/self.gpu = 1/g' setup.py && cd .. && \
        cd python-package &&  sed -i 's/self\.precompile \= 0/self.precompile = 1/g' setup.py && cd .. && \
(END)
```

All the above is inside an arch != "ppc64le" so literally nothing changed between commits.  Must be external change, like versioning, but didn't find it so far.

**Comment by pseudotensor** [comment]
The error:

```
03:18:38 h2o4gpu/cluster/_k_means_elkan.c: In function
â<U+0080><U+0098>__pyx_pf_7h2o4gpu_7cluster_14_k_means_elkan_k_means_elkanâ<U+0080><U+0099>:
03:18:38 h2o4gpu/cluster/_k_means_elkan.c:3890:7: error: too many arguments to
function â<U+0080><U+0098>__Pyx_PyObject_to_MemoryviewSlice_dsds_floatâ<U+0080><U+0099>
03:18:38        __pyx_t_8 = __Pyx_PyObject_to_MemoryviewSlice_dsds_float
(__pyx_v_arg, 0);
03:18:38        ^
03:18:38 h2o4gpu/cluster/_k_means_elkan.c:2169:41: note: declared here
03:18:38  static CYTHON_INLINE __Pyx_memviewslice
__Pyx_PyObject_to_MemoryviewSlice_dsds_float(PyObject *);
03:18:38                                          ^
03:18:38 h2o4gpu/cluster/_k_means_elkan.c:3912:7: error: too many arguments to
function â<U+0080><U+0098>__Pyx_PyObject_to_MemoryviewSlice_dsds_doubleâ<U+0080><U+0099>
03:18:38        __pyx_t_8 = __Pyx_PyObject_to_MemoryviewSlice_dsds_double
(__pyx_v_arg, 0);
03:18:38        ^
03:18:38 h2o4gpu/cluster/_k_means_elkan.c:2172:41: note: declared here
03:18:38  static CYTHON_INLINE __Pyx_memviewslice
__Pyx_PyObject_to_MemoryviewSlice_dsds_double(PyObject *);
03:18:38                                          ^
03:18:38 error: Command "gcc -pthread -B /opt/h2oai/h2o4gpu/python/
compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -
Wstrict-prototypes -fPIC -I/opt/h2oai/h2o4gpu/python/lib/python3.6/site-
packages/numpy/core/include -I/opt/h2oai/h2o4gpu/python/lib/python3.6/site-
packages/numpy/core/include -I/opt/h2oai/h2o4gpu/python/include/python3.6m -
c h2o4gpu/cluster/_k_means_elkan.c -o build/temp.linux-ppc64le-3.6/h2o4gpu/
cluster/_k_means_elkan.o -MMD -MF build/temp.linux-ppc64le-3.6/h2o4gpu/cluster/
_k_means_elkan.o.d" failed with exit status 1

```

**Comment by pseudotensor** [comment]
Tom suggested:
```
 # Convert .py files to .c and compile to .so
        ext_modules=cythonize(extensions,
                              compiler_directives={
                                  'always_allow_keywords': True
                              }),
```

But that failed to build:

https://github.com/h2oai/h2o4gpu/pull/644

**Comment by pseudotensor** [comment]
http://mr-0xc1:8080/job/h2o4gpu-ppc64le-cuda9/job/master/30/consoleFull

**Comment by mdymczyk** [comment]
So the above seems to happen on the px01 machine, on the GPU enabled Power box we have I noticed a different issue http://mr-0xc1:8080/job/h2o4gpu-ppc64le-cuda9/job/master/29/consoleFull

```
15:18:47     Did not find libzmq via pkg-config.
15:18:47     {'libraries': ['zmq'], 'include_dirs': [], 'library_dirs': [], 'runtime_library_dirs': [], 'extra_link_args': []}
15:18:47     gcc -pthread -B /opt/h2oai/h2o4gpu/python/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -c build/temp.linux-ppc64le-3.6/scratch/check_sys_un.c -o build/temp.linux-ppc64le-3.6/scratch/check_sys_un.o
15:18:47     gcc -pthread -B /opt/h2oai/h2o4gpu/python/compiler_compat -Wl,--sysroot=/ build/temp.linux-ppc64le-3.6/scratch/check_sys_un.o -o build/temp.linux-ppc64le-3.6/scratch/check_sys_un
15:18:47     ************************************************
15:18:47     Configure: Autodetecting ZMQ settings...
15:18:47         Custom ZMQ dir:
15:18:47     creating build/temp.linux-ppc64le-3.6/scratch/tmp
15:18:47     cc -c /tmp/timer_create98s9tok6.c -o build/temp.linux-ppc64le-3.6/scratch/tmp/timer_create98s9tok6.o
15:18:47     cc build/temp.linux-ppc64le-3.6/scratch/tmp/timer_create98s9tok6.o -o build/temp.linux-ppc64le-3.6/scratch/a.out
15:18:47     build/temp.linux-ppc64le-3.6/scratch/tmp/timer_create98s9tok6.o: In function `main':
15:18:47     timer_create98s9tok6.c:(.text+0x28): undefined reference to `timer_create'
15:18:47     collect2: error: ld returned 1 exit status
15:18:47     gcc -pthread -B /opt/h2oai/h2o4gpu/python/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Izmq/utils -Izmq/backend/cython -Izmq/devices -c build/temp.linux-ppc64le-3.6/scratch/vers.c -o build/temp.linux-ppc64le-3.6/scratch/vers.o
15:18:47     build/temp.linux-ppc64le-3.6/scratch/vers.c:4:17: fatal error: zmq.h: No such file or directory
15:18:47      #include "zmq.h"
15:18:47                      ^
15:18:47     compilation terminated.
15:18:47     
15:18:47     error: command 'gcc' failed with exit status 1
15:18:47     
15:18:47     Failed with default libzmq, trying again with /usr/local
15:18:47     {'libraries': ['zmq'], 'include_dirs': ['/usr/local/include'], 'library_dirs': ['/usr/local/lib'], 'runtime_library_dirs': ['/usr/local/lib'], 'extra_link_args': []}
15:18:47     ************************************************
15:18:47     Configure: Autodetecting ZMQ settings...
15:18:47         Custom ZMQ dir:       /usr/local
15:18:47     cc -c /tmp/timer_createdhg0ij3q.c -o build/temp.linux-ppc64le-3.6/scratch/tmp/timer_createdhg0ij3q.o
15:18:47     Assembler messages:
15:18:47     Fatal error: can't create build/temp.linux-ppc64le-3.6/scratch/tmp/timer_createdhg0ij3q.o: No such file or directory
15:18:47     gcc -pthread -B /opt/h2oai/h2o4gpu/python/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Izmq/utils -Izmq/backend/cython -Izmq/devices -c build/temp.linux-ppc64le-3.6/scratch/vers.c -o build/temp.linux-ppc64le-3.6/scratch/vers.o
15:18:47     build/temp.linux-ppc64le-3.6/scratch/vers.c:4:17: fatal error: zmq.h: No such file or directory
15:18:47      #include "zmq.h"
15:18:47                      ^
15:18:47     compilation terminated.
15:18:47     
15:18:47     error: command 'gcc' failed with exit status 1
15:18:47     
15:18:47     ************************************************
15:18:47     Warning: Couldn't find an acceptable libzmq on the system.
15:18:47     
15:18:47     If you expected pyzmq to link against an installed libzmq, please check to make sure:
15:18:47     
15:18:47         * You have a C compiler installed
15:18:47         * A development version of Python is installed (including headers)
15:18:47         * A development version of ZMQ >= 3.2 is installed (including headers)
15:18:47         * If ZMQ is not in a default location, supply the argument --zmq=<path>
15:18:47         * If you did recently install ZMQ to a default location,
15:18:47           try rebuilding the ld cache with `sudo ldconfig`
15:18:47           or specify zmq's location with `--zmq=/usr/local`
15:18:47     
15:18:47     You can skip all this detection/waiting nonsense if you know
15:18:47     you want pyzmq to bundle libzmq as an extension by passing:
15:18:47     
15:18:47         `--zmq=bundled`
15:18:47     
15:18:47     I will now try to build libzmq as a Python extension
15:18:47     unless you interrupt me (^C) in the next 10 seconds...
15:18:47     
15:18:47     
    10...
     9...
     8...
     7...
     6...
     5...
     4...
     3...
     2...
     1...
15:18:47     ************************************************
15:18:47     Using bundled libzmq
15:18:47     already have bundled/zeromq
15:18:47     already have platform.hpp
15:18:47     ************************************************
15:18:47     checking for timer_create
15:18:47     creating build/temp.linux-ppc64le-3.6/tmp
15:18:47     cc -c /tmp/timer_createry_12djx.c -o build/temp.linux-ppc64le-3.6/tmp/timer_createry_12djx.o
15:18:47     cc build/temp.linux-ppc64le-3.6/tmp/timer_createry_12djx.o -o build/temp.linux-ppc64le-3.6/a.out
15:18:47     build/temp.linux-ppc64le-3.6/tmp/timer_createry_12djx.o: In function `main':
15:18:47     timer_createry_12djx.c:(.text+0x28): undefined reference to `timer_create'
15:18:47     collect2: error: ld returned 1 exit status
15:18:47     no timer_create, linking librt
15:18:47     ************************************************
15:18:47     building 'zmq.libzmq' extension
15:18:47     creating build/temp.linux-ppc64le-3.6/buildutils
15:18:47     creating build/temp.linux-ppc64le-3.6/bundled
15:18:47     creating build/temp.linux-ppc64le-3.6/bundled/zeromq
15:18:47     creating build/temp.linux-ppc64le-3.6/bundled/zeromq/src
15:18:47     gcc -pthread -B /opt/h2oai/h2o4gpu/python/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_EPOLL=1 -Ibundled/zeromq/include -Ibundled -I/opt/h2oai/h2o4gpu/python/include/python3.6m -c buildutils/initlibzmq.c -o build/temp.linux-ppc64le-3.6/buildutils/initlibzmq.o
15:18:47     gcc -pthread -B /opt/h2oai/h2o4gpu/python/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_EPOLL=1 -Ibundled/zeromq/include -Ibundled -I/opt/h2oai/h2o4gpu/python/include/python3.6m -c bundled/zeromq/src/socket_base.cpp -o build/temp.linux-ppc64le-3.6/bundled/zeromq/src/socket_base.o
15:18:47     cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
15:18:47     In file included from bundled/zeromq/src/options.hpp:38:0,
15:18:47                      from bundled/zeromq/src/own.hpp:37,
15:18:47                      from bundled/zeromq/src/socket_base.hpp:37,
15:18:47                      from bundled/zeromq/src/socket_base.cpp:50:
15:18:47     bundled/zeromq/src/atomic_ptr.hpp: In member function 'int zmq::atomic_value_t::load() const':
15:18:47     bundled/zeromq/src/atomic_ptr.hpp:271:9: error: invalid initialization of reference of type 'zmq::mutex_t&' from expression of type 'const zmq::mutex_t'
15:18:47              );
15:18:47              ^
15:18:47     bundled/zeromq/src/atomic_ptr.hpp:116:14: error: in passing argument 4 of 'void* zmq::atomic_cas(void* volatile*, void*, void*, zmq::mutex_t&)'
15:18:47      inline void *atomic_cas (void *volatile *ptr_,
15:18:47                   ^
15:18:47     bundled/zeromq/src/atomic_ptr.hpp:273:5: warning: control reaches end of non-void function [-Wreturn-type]
15:18:47          }
15:18:47          ^
15:18:47     error: command 'gcc' failed with exit status 1
15:18:47     
15:18:47     ----------------------------------------
15:18:47 Command "/opt/h2oai/h2o4gpu/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-to3fqj3u/pyzmq/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-uhcrftk0-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-to3fqj3u/pyzmq/
15:18:47 You are using pip version 9.0.1, however version 10.0.1 is available.
15:18:47 You should consider upgrading via the 'pip install --upgrade pip' command.
15:18:47 The command '/bin/sh -c pip install -r requirements_buildonly.txt' returned a non-zero code: 1
```

**Comment by pseudotensor** [comment]
That may be more recent, as it seems to be due to xgboost pip install line I added in Makefile2.  It works fine with x86/centos, but maybe some things there are not needed for xgboost as we use it.

**Comment by trstovall** [comment]
I resolved the pyzmq build error on ppc64le by installing libzmq3-dev (`apt-get`) instead of libzmq-dev before `pip install -U pyzmq`.

**Comment by pseudotensor** [comment]
Great, thanks!  Was that a new issue or did the build fully pass?

**Comment by trstovall** [comment]
I think a new version of pyzmq was pushed to PyPI which looks for libzmq3-dev to be installed.  When it is not found, it attempts to compile libzmq as a C extension, which fails on power8.

**Comment by hemenkapadia** [comment]
@CreatureDev , I still see ppc builds failing for PR-671 due to llvmlite. Have verified that the same code works fine for x86_64.

Any thoughts ?

```
17:51:05   Complete output from command /opt/h2oai/h2o4gpu/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-pvcub999/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpqmr2_x8xpip-wheel- --python-tag cp36:
17:51:05   running bdist_wheel
17:51:05   /opt/h2oai/h2o4gpu/python/bin/python /tmp/pip-build-pvcub999/llvmlite/ffi/build.py
17:51:05   LLVM version... 4.0.1
17:51:05   
17:51:05   Traceback (most recent call last):
17:51:05     File "/tmp/pip-build-pvcub999/llvmlite/ffi/build.py", line 141, in <module>
17:51:05       main()
17:51:05     File "/tmp/pip-build-pvcub999/llvmlite/ffi/build.py", line 131, in main
17:51:05       main_posix('linux', '.so')
17:51:05     File "/tmp/pip-build-pvcub999/llvmlite/ffi/build.py", line 105, in main_posix
17:51:05       raise RuntimeError(msg)
17:51:05   RuntimeError: Building llvmlite requires LLVM 5.0.x. Be sure to set LLVM_CONFIG to the right executable path.
17:51:05   Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.
17:51:05   
17:51:05   error: command '/opt/h2oai/h2o4gpu/python/bin/python' failed with exit status 1
17:51:05   
17:51:05   ----------------------------------------
17:51:05   Failed building wheel for llvmlite
```
