### ISSUE TITLE
No module named 'h2o4gpu.utils.murmurhash'

### ISSUE THREAD

**Issue by nasica88** [h2oai/h2o4gpu#654]
### Environment (for bugs)

- **OS platform, distribution and version :  Redhat 7.5 ALT ppc64le
- **Installed from (source or binary)**: from source (pip install -i https://pypi.anaconda.org/gpuopenanalytics/simple h2o4gpu)
- **Version**: 0.0.4
- **Python version (optional)**: python 3.6 from Anaconda 5.0 
- **CUDA/cuDNN version**: CUDA 9.2 cuDNN 7.1
- **GPU model (optional)**:  V100
- **CPU model**:  POWER9
- **RAM available**: 512GB

### Description

$ pip list | grep h2o
h2o4gpu                            0.1.0

$ python
Python 3.6.2 |Anaconda custom (64-bit)| (default, Sep 15 2017, 20:38:23)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h2o4gpu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.6/site-packages/h2o4gpu/__init__.py", line 11, in <module>
    from .solvers.pogs import Pogs
  File "/root/anaconda3/lib/python3.6/site-packages/h2o4gpu/solvers/__init__.py", line 8, in <module>
    from ..solvers.elastic_net import ElasticNetH2O
  File "/root/anaconda3/lib/python3.6/site-packages/h2o4gpu/solvers/elastic_net.py", line 14, in <module>
    from h2o4gpu.linear_model import coordinate_descent as sk
  File "/root/anaconda3/lib/python3.6/site-packages/h2o4gpu/linear_model/__init__.py", line 12, in <module>
    from .base import LinearRegressionSklearn
  File "/root/anaconda3/lib/python3.6/site-packages/h2o4gpu/linear_model/base.py", line 28, in <module>
    from ..base import BaseEstimator, ClassifierMixin, RegressorMixin
  File "/root/anaconda3/lib/python3.6/site-packages/h2o4gpu/base.py", line 12, in <module>
    from .utils.fixes import signature
  File "/root/anaconda3/lib/python3.6/site-packages/h2o4gpu/utils/__init__.py", line 10, in <module>
    from .murmurhash import murmurhash3_32
ModuleNotFoundError: No module named 'h2o4gpu.utils.murmurhash'

I tried installing spacy, during which murmurhash is also installed, but it did not help.

$ pip list | grep murmur
murmurhash                         0.28.0

$ pip list | grep spacy
spacy                              2.0.12

**Comment by nasica88** [comment]
I built the required version of Cython (0.27.3) from source and retried make fullinstall, but it ends up with the same error.

$ git clone --recursive https://github.com/cython/cython.git

$ python setup.py install

$ pip list | grep Cython
Cython                             0.27.3

$ cd /home/data/h2o4gpu && make fullinstall
...
  Using cached https://files.pythonhosted.org/packages/25/35/de0609b03a1168726a86b43e178c9d857ca5272828e8f025255c0426be4b/h2o-3.18.0.10.tar.gz
Collecting pandas==0.22.0 (from -r requirements.txt (line 20))
  Using cached https://files.pythonhosted.org/packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz
  Could not find a version that satisfies the requirement Cython (from versions: )
No matching distribution found for Cython
make: *** [deps_install] Error 1

**Comment by nasica88** [comment]
I could bypass this trouble by editing the following files.  In these files, I set all cython entries with "Cython==0.27.3".   

./scikit-learn/build_tools/appveyor/requirements.txt 
./src/interface_py/requirements_buildonly.txt 
./xgboost/requirements_buildonly.txt
